import {
  CircleX,
  MailOpen,
  MapPin,
  PhoneCall,
  ShoppingBag,
  Settings,
  User,
  SmartphoneCharging,
  Tv,
  HeartPulse,
  Baby,
  MonitorSmartphone,
  PawPrint,
  House,
  UserRound,
  Watch,
  LandPlot,
  Workflow,
} from "lucide-react";
import { FaInstagram, FaFacebookF, FaXTwitter } from "react-icons/fa6";

export const headerContent = {
  nav: [
    {
      label: "Home",
      url: "/",
    },
    {
      label: "Shop",
      url: "#",
      items: [],
    },
    {
      label: "About",
      url: "/about",
    },
    {
      label: "Blog",
      url: "/blog",
    },
    {
      label: "Contact",
      url: "/contact",
    },
  ],
  user: [
    {
      label: "Profile",
      url: "/profile/information",
      Icon: User,
    },
    {
      label: "Orders",
      url: "/profile/orders",
      Icon: ShoppingBag,
    },
    {
      label: "Reviews",
      url: "/profile/reviews/",
      Icon: CircleX,
    },
    {
      label: "Settings",
      url: "/profile/settings",
      Icon: Settings,
    },
  ],
};

export const footerContent: FooterContentItem[] = [
  {
    title: "Logo",
    items: [
      {
        label: "(704) 555-0127",
        url: "tel:+1-704-555-0127",
        Icon: PhoneCall,
      },
      {
        label: "info@krist.com",
        url: "mailto:info@krist.com",
        Icon: MailOpen,
      },
      {
        label: "123 Main St, Anytown, USA",
        url: "https://maps.google.com/maps?q=123%20Main%20St%2C%20Anytown%2C%20USA",
        Icon: MapPin,
        external: true,
      },
    ],
  },
  {
    title: "Account",
    items: [
      {
        label: "My Account",
        url: "/account",
      },
      {
        label: "Cart",
        url: "/cart",
      },
      {
        label: "Wishlist ",
        url: "/wishlist",
      },
      {
        label: "Shop",
        url: "/shop",
      },
    ],
  },
  {
    title: "Quick Link",
    items: [
      { label: "Privacy Policy", url: "/privacy" },
      { label: "Terms of Use", url: "/terms" },
      { label: "FAQ", url: "/delivery" },
      { label: "Contact", url: "/career" },
    ],
  },
  {
    title: "Newsletter",
    items: [],
  },
];

export const paymentMethods = [
  { label: "Visa", url: "/assets/icons/visa-pay.svg" },
  { label: "MasterCard", url: "/assets/icons/master-pay.svg" },
  { label: "Google Pay", url: "/assets/icons/g-pay.svg" },
  { label: "PayPal", url: "/assets/icons/paypal-pay.svg" },
  { label: "Apple Pay", url: "/assets/icons/apple-pay.svg" },
];

export const socialLinks = [
  {
    label: "Instagram",
    url: "https://www.instagram.com/krist_official/",
    Icon: FaInstagram,
  },
  {
    label: "Facebook",
    url: "https://www.facebook.com/krist.official/",
    Icon: FaFacebookF,
  },
  {
    label: "Twitter",
    url: "https://twitter.com/kristofficial/",
    Icon: FaXTwitter,
  },
];

export const heroImages = Array.from({ length: 7 }, (_, index) => ({
  src: `/assets/images/hero-image-${index + 1}.png`,
  alt: `Hero Image ${index + 1}`,
}));

export const sortTypes = [
  {
    label: "Date created (newest)",
    value: "$createdAt-desc",
  },
  {
    label: "Created Date (oldest)",
    value: "$createdAt-asc",
  },
  {
    label: "Name (A-Z)",
    value: "name-asc",
  },
  {
    label: "Name (Z-A)",
    value: "name-desc",
  },
  {
    label: "Size (Highest)",
    value: "size-desc",
  },
  {
    label: "Size (Lowest)",
    value: "size-asc",
  },
];

export const categories: Category[] = [
  {
    label: "Electronic Accessories",
    url: "/",
    Icon: SmartphoneCharging,
    items: [
      {
        label: "Mobile Accessories",
        url: "/",
        items: [
          { label: "Tablet Accessories", url: "/" },
          { label: "Cables & Converters", url: "/" },
          { label: "Phone Cases", url: "/" },
          { label: "Car Mounts", url: "/" },
          { label: "Parts & Tools", url: "/" },
          { label: "Screen Protectors", url: "/" },
          { label: "Power Banks", url: "/" },
          { label: "Phone Camera Flash Lights", url: "/" },
          { label: "Wireless Chargers", url: "/" },
          { label: "Selfie Sticks", url: "/" },
          { label: "Car Chargers", url: "/" },
          { label: "Wall Chargers", url: "/" },
        ],
      },
      {
        label: "Camera Accessories",
        url: "/",
        items: [
          { label: "Gimbals & Stabilizers", url: "/" },
          { label: "Action Camera Accessories", url: "/" },
          { label: "Lenses", url: "/" },
          { label: "Tripods & Monopods", url: "/" },
          { label: "Memory Cards", url: "/" },
          { label: "Batteries", url: "/" },
          { label: "Lighting & Studio Equipment", url: "/" },
          { label: "Camera Cases, Covers and Bags", url: "/" },
        ],
      },
      {
        label: "Wearable",
        url: "/",
        items: [
          { label: "Fitness & Activity Trackers", url: "/" },
          { label: "Virtual Reality", url: "/" },
        ],
      },
      {
        label: "Network Components",
        url: "/",
        items: [{ label: "Access Points", url: "/" }],
      },
      {
        label: "Computer Components",
        url: "/",
        items: [
          { label: "Motherboards", url: "/" },
          { label: "Processors", url: "/" },
          { label: "Fans & Heatsinks", url: "/" },
          { label: "Graphic Cards", url: "/" },
          { label: "Desktop Casings", url: "/" },
        ],
      },
      {
        label: "Headphones & Headsets",
        url: "/",
        items: [
          { label: "Bluetooth Headsets", url: "/" },
          { label: "Wired Headsets", url: "/" },
          { label: "In-Ear Headphones", url: "/" },
          { label: "Over-The-Ear Headphones", url: "/" },
          { label: "Headphones & Headsets Access.", url: "/" },
          { label: "Wireless Earbuds", url: "/" },
          { label: "Mono Headsets", url: "/" },
        ],
      },
      {
        label: "Printers",
        url: "/",
        items: [
          { label: "Ink & Toners", url: "/" },
          { label: "Fax Machines", url: "/" },
        ],
      },
      {
        label: "Storage",
        url: "/",
        items: [
          { label: "Internal Hard Drives", url: "/" },
          { label: "Storage for Mac", url: "/" },
          { label: "Flash Drives", url: "/" },
          { label: "OTG Drives", url: "/" },
          { label: "External Hard Drives", url: "/" },
        ],
      },
      { label: "Portable Speakers", url: "/", items: [] },
      {
        label: "Gaming Accessories",
        url: "/",
        items: [
          { label: "Gaming Mouse", url: "/" },
          { label: "Gaming Keyboards", url: "/" },
          { label: "Gaming Headsets", url: "/" },
        ],
      },
      { label: "Monitors & Accessories", url: "/", items: [] },
      {
        label: "Computer Accessories",
        url: "/",
        items: [
          { label: "Mac Accessories", url: "/" },
          { label: "Mouse", url: "/" },
          { label: "Adapters & Cables", url: "/" },
          { label: "PC Audio", url: "/" },
          { label: "Cooling Pads/Cooling Stands", url: "/" },
          { label: "Keyboards", url: "/" },
        ],
      },
    ],
  },
  {
    label: "TV & Home Appliances",
    url: "/",
    Icon: Tv,
    items: [
      { label: "Air Conditioner", url: "/", items: [] },
      { label: "Washing Machine", url: "/", items: [] },
      {
        label: "Refrigerators & Freezers",
        url: "/",
        items: [{ label: "Freezers", url: "/" }],
      },
      {
        label: "Cooling & Heating",
        url: "/",
        items: [
          { label: "Air Cooler", url: "/" },
          { label: "Air Purifier", url: "/" },
          { label: "Dehumidifier", url: "/" },
          { label: "Humidifier", url: "/" },
          { label: "Fan", url: "/" },
          { label: "Room Heater", url: "/" },
          { label: "Water Heater", url: "/" },
        ],
      },
      {
        label: "Irons & Garment Care",
        url: "/",
        items: [
          { label: "Irons", url: "/" },
          { label: "Garment Steamer", url: "/" },
          { label: "Sewing Machine", url: "/" },
        ],
      },
      {
        label: "Vacuums & Floor Care",
        url: "/",
        items: [
          { label: "Electric Brooms", url: "/" },
          { label: "Steam Mops", url: "/" },
          { label: "Floor Polisher", url: "/" },
          { label: "Vacuum Cleaner", url: "/" },
        ],
      },
      {
        label: "Kitchen Appliances",
        url: "/",
        items: [
          { label: "Microwave", url: "/" },
          { label: "Water Dispensers", url: "/" },
          { label: "Dishwashers", url: "/" },
          { label: "Cooktop & Range", url: "/" },
          { label: "Oven", url: "/" },
          { label: "Air & Deep Fryers", url: "/" },
          { label: "Specialty Cookware", url: "/" },
          { label: "Juicer & Fruit Extraction", url: "/" },
          { label: "Blender, Mixer & Grinder", url: "/" },
          { label: "Electric Kettle", url: "/" },
          { label: "Pressure Cookers", url: "/" },
          { label: "Rice Cooker", url: "/" },
        ],
      },
      {
        label: "Home Audio & Theater",
        url: "/",
        items: [
          { label: "Soundbar Speakers", url: "/" },
          { label: "Live Sound & Stage Equipment", url: "/" },
          { label: "Home Entertainment", url: "/" },
          { label: "Home Theater Systems", url: "/" },
        ],
      },
      {
        label: "Televisions",
        url: "/",
        items: [
          { label: "LED Televisions", url: "/" },
          { label: "Smart Televisions", url: "/" },
        ],
      },
      {
        label: "Projectors & Players",
        url: "/",
        items: [
          { label: "Projectors", url: "/" },
          { label: "Blu Ray & DVD Players", url: "/" },
        ],
      },
      {
        label: "Generator, UPS & Solar",
        url: "/",
        items: [
          { label: "Solar Inverters", url: "/" },
          { label: "Generators", url: "/" },
          { label: "UPS", url: "/" },
        ],
      },
      {
        label: "TV Accessories",
        url: "/",
        items: [
          { label: "Antennas", url: "/" },
          { label: "TV Receivers", url: "/" },
          { label: "Cables", url: "/" },
          { label: "3D Glasses", url: "/" },
          { label: "TV Remote Controllers", url: "/" },
          { label: "Wall Mounts & Protectors", url: "/" },
          { label: "TV Adapters", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Health & Beauty",
    url: "/",
    Icon: HeartPulse,
    items: [
      {
        label: "Men's Care",
        url: "/",
        items: [{ label: "Shaving & Grooming", url: "/" }],
      },
      {
        label: "Medical Supplies",
        url: "/",
        items: [
          { label: "Stethoscopes", url: "/" },
          { label: "Surgical Masks", url: "/" },
          { label: "Health Monitors & Tests", url: "/" },
          { label: "Ointments and Creams", url: "/" },
          { label: "Nebulizer & Aspirators", url: "/" },
          { label: "Health Accessories", url: "/" },
          { label: "First Aid Supplies", url: "/" },
        ],
      },
      {
        label: "Personal Care",
        url: "/",
        items: [
          { label: "Adult Diapers", url: "/" },
          { label: "Oral Care", url: "/" },
          { label: "Eye Care", url: "/" },
          { label: "Pads & Tampons", url: "/" },
          { label: "Menstrual Cups", url: "/" },
          { label: "Deodorants", url: "/" },
          { label: "Personal Safety & Security", url: "/" },
          { label: "Ear Care", url: "/" },
        ],
      },
      {
        label: "Hair Care",
        url: "/",
        items: [
          { label: "Oil & Serums", url: "/" },
          { label: "Hair Care Accessories", url: "/" },
          { label: "Shampoo & Conditioner", url: "/" },
          { label: "Hair Treatments", url: "/" },
          { label: "Hair Styling", url: "/" },
          { label: "Hair Coloring", url: "/" },
        ],
      },
      {
        label: "Beauty Tools",
        url: "/",
        items: [
          { label: "Foot Relief Tools", url: "/" },
          { label: "Slimming & Electric Massagers", url: "/" },
          { label: "Hair Removal Appliances", url: "/" },
          { label: "Hair Styling Appliances", url: "/" },
          { label: "Skin Care Tools", url: "/" },
        ],
      },
      {
        label: "Makeup",
        url: "/",
        items: [
          { label: "Bulk Deals", url: "/" },
          { label: "Eyes", url: "/" },
          { label: "Makeup Accessories", url: "/" },
          { label: "Lips", url: "/" },
          { label: "Nails", url: "/" },
          { label: "Makeup Removers", url: "/" },
          { label: "Makeup Palettes & Sets", url: "/" },
          { label: "Face", url: "/" },
        ],
      },
      {
        label: "Fragrances",
        url: "/",
        items: [
          { label: "Women", url: "/" },
          { label: "Men", url: "/" },
          { label: "Unisex", url: "/" },
        ],
      },
      {
        label: "Bath & Body",
        url: "/",
        items: [
          { label: "Hand Care", url: "/" },
          { label: "Talcum Powder", url: "/" },
          { label: "Foot Care", url: "/" },
          { label: "Body Moisturizers", url: "/" },
          { label: "Hair Removal", url: "/" },
          { label: "Body Soaps & Shower Gels", url: "/" },
          { label: "Body Scrubs", url: "/" },
          { label: "Bath & Body Accessories", url: "/" },
          { label: "Body & Massage Oils", url: "/" },
        ],
      },
      {
        label: "Sexual Wellness",
        url: "/",
        items: [
          { label: "Lubricants", url: "/" },
          { label: "Condoms", url: "/" },
        ],
      },
      {
        label: "Skin Care",
        url: "/",
        items: [
          { label: "Moisturizers and Cream", url: "/" },
          { label: "Lip Balm & Treatment", url: "/" },
          { label: "Sunscreen & Aftersun", url: "/" },
          { label: "Face Mask & Packs", url: "/" },
          { label: "Face Scrubs & Exfoliators", url: "/" },
          { label: "Facial Cleansers", url: "/" },
          { label: "Toner & Mists", url: "/" },
          { label: "Serum & Essence", url: "/" },
          { label: "Eye Care", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Mother & Baby",
    url: "/",
    Icon: Baby,
    items: [
      {
        label: "Clothing & Accessories",
        url: "/",
        items: [
          { label: "Newborn", url: "/" },
          { label: "Accessories", url: "/" },
          { label: "New born sets & Packs", url: "/" },
          { label: "Girls (Under 3 Years)", url: "/" },
          { label: "Boys (Under 3 Years)", url: "/" },
          { label: "New born bodysuits", url: "/" },
        ],
      },
      {
        label: "Maternity Care",
        url: "/",
        items: [
          { label: "Pregnancy Pillows", url: "/" },
          { label: "Maternity Accessories", url: "/" },
          { label: "Breast Pumps", url: "/" },
          { label: "Nursing Covers", url: "/" },
          { label: "Maternity Wear", url: "/" },
          { label: "Nipple Care", url: "/" },
          { label: "Breast Shells", url: "/" },
        ],
      },
      {
        label: "Baby Gear",
        url: "/",
        items: [
          { label: "Backpacks & Carriers", url: "/" },
          { label: "Swings, Jumpers & Bouncers", url: "/" },
          { label: "Harnesses & Leashes", url: "/" },
          { label: "Walkers", url: "/" },
          { label: "Car Seats", url: "/" },
          { label: "Strollers", url: "/" },
          { label: "Highchairs & Booster Seats", url: "/" },
          { label: "Baby Safety", url: "/" },
          { label: "Baby Monitor", url: "/" },
          { label: "Kids Bag", url: "/" },
        ],
      },
      {
        label: "Remote Control & Vehicles",
        url: "/",
        items: [
          { label: "Play Vehicles", url: "/" },
          { label: "RC Vehicles & Batteries", url: "/" },
          { label: "Drones & Accessories", url: "/" },
          { label: "Die-Cast Vehicles", url: "/" },
          { label: "Play Trains & Railway Sets", url: "/" },
        ],
      },
      {
        label: "Feeding",
        url: "/",
        items: [
          { label: "Bottle-Feeding", url: "/" },
          { label: "Breastfeeding", url: "/" },
          { label: "Food Blenders", url: "/" },
          { label: "Utensils", url: "/" },
          { label: "Pacifiers & Teethers", url: "/" },
        ],
      },
      {
        label: "Milk Formula & Baby Food",
        url: "/",
        items: [
          { label: "Toddler Milk (1 - under 3 yrs)", url: "/" },
          { label: "Maternal", url: "/" },
          { label: "Infant Milk (0-6 Months)", url: "/" },
          { label: "Infant Milk (6-12 Months)", url: "/" },
          { label: "Growing-up Milk (3yrs +)", url: "/" },
          { label: "Baby & Toddler Foods", url: "/" },
        ],
      },
      {
        label: "Diapering & Potty",
        url: "/",
        items: [
          { label: "Disposable diapers", url: "/" },
          { label: "Diaper Bags", url: "/" },
          { label: "Diapering Care", url: "/" },
          { label: "Changing Tables, Pads & Kits", url: "/" },
          { label: "Cloth Diapers & Accessories", url: "/" },
          { label: "Wipes & Holders", url: "/" },
          { label: "Potty Training", url: "/" },
        ],
      },
      {
        label: "Nursery",
        url: "/",
        items: [
          { label: "Storage & Organization", url: "/" },
          { label: "Nursery Decor", url: "/" },
          { label: "Baby Furniture", url: "/" },
          { label: "Mattresses & Bedding", url: "/" },
        ],
      },
      {
        label: "Sports & Outdoor Play",
        url: "/",
        items: [
          { label: "Inflatable Bouncers", url: "/" },
          { label: "Fidget Spinners", url: "/" },
          { label: "Swimming Pool & Water Toys", url: "/" },
        ],
      },
      {
        label: "Baby & Toddler Toys",
        url: "/",
        items: [
          { label: "Activity Gym & Playmats", url: "/" },
          { label: "Bath Toys", url: "/" },
          { label: "Crib Toys & Attachments", url: "/" },
          { label: "Push & Pull Toys", url: "/" },
          { label: "Music & Sound", url: "/" },
          { label: "Early Development Toys", url: "/" },
          { label: "Rattles", url: "/" },
          { label: "Building Blocks Toys", url: "/" },
        ],
      },
      {
        label: "Baby Personal Care",
        url: "/",
        items: [
          { label: "Shampoo & Conditioners", url: "/" },
          { label: "Bathing Tubs & Seats", url: "/" },
          { label: "Grooming & Healthcare Kits", url: "/" },
          { label: "Baby Bath Mats", url: "/" },
          { label: "Skin Care", url: "/" },
          { label: "Soaps, Cleansers & Bodywash", url: "/" },
          { label: "Washcloths & Towels", url: "/" },
          { label: "Toothbrushes & Toothpaste", url: "/" },
        ],
      },
      {
        label: "Toys & Games",
        url: "/",
        items: [
          { label: "Stuffed Toys", url: "/" },
          { label: "Puzzle & Boardgames", url: "/" },
          { label: "Pretend Play", url: "/" },
          { label: "Slime & Squishy Toys", url: "/" },
          { label: "Learning & Education", url: "/" },
          { label: "Blocks & Building toys", url: "/" },
          { label: "Dolls & Accessories", url: "/" },
          { label: "Action Figures & Collectibles", url: "/" },
          { label: "Arts & Crafts for Kids", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Electronic Devices",
    url: "/",
    Icon: MonitorSmartphone,
    items: [
      { label: "Feature Phones", url: "/", items: [] },
      {
        label: "Krist Like New",
        url: "/",
        items: [
          { label: "Like New Phones", url: "/" },
          { label: "Like New Smartwatches", url: "/" },
          { label: "Like New Laptops", url: "/" },
          { label: "Like New Tablets", url: "/" },
          { label: "Like New Speakers", url: "/" },
          { label: "Like New Airbuds", url: "/" },
        ],
      },
      {
        label: "Security Cameras",
        url: "/",
        items: [{ label: "IP Security Cameras", url: "/" }],
      },
      {
        label: "Gaming Consoles",
        url: "/",
        items: [
          { label: "Playstation Games", url: "/" },
          { label: "PlayStation Consoles", url: "/" },
          { label: "Playstation Controllers", url: "/" },
          { label: "Nintendo Games", url: "/" },
          { label: "Xbox Games", url: "/" },
        ],
      },
      {
        label: "Smart Phones",
        url: "/",
        items: [
          { label: "Nokia Mobiles", url: "/" },
          { label: "Honor Mobiles", url: "/" },
          { label: "Infinix Mobiles", url: "/" },
          { label: "Realme Mobiles", url: "/" },
          { label: "Redmi Mobiles", url: "/" },
          { label: "Oneplus Mobiles", url: "/" },
          { label: "Oppo Mobile Phones", url: "/" },
          { label: "Apple iPhones", url: "/" },
          { label: "Tecno Mobiles", url: "/" },
          { label: "Samsung Mobile Phones", url: "/" },
          { label: "Vivo Mobiles", url: "/" },
        ],
      },
      {
        label: "Cameras & Drones",
        url: "/",
        items: [
          { label: "Drones", url: "/" },
          { label: "Point & Shoot", url: "/" },
          { label: "DSLR", url: "/" },
          { label: "Instant Cameras", url: "/" },
          { label: "Video Camera", url: "/" },
        ],
      },
      { label: "Smart Watches", url: "/", items: [] },
      { label: "Monitors", url: "/", items: [] },
      { label: "Landline Phones", url: "/", items: [] },
      {
        label: "Laptops",
        url: "/",
        items: [
          { label: "Refurbished Laptops", url: "/" },
          { label: "Traditional Laptops", url: "/" },
        ],
      },
      {
        label: "Desktops",
        url: "/",
        items: [{ label: "All-In-One", url: "/" }],
      },
    ],
  },
  {
    label: "Groceries & Pets",
    url: "/",
    Icon: PawPrint,
    items: [
      {
        label: "Frozen Food",
        url: "/",
        items: [
          { label: "Other Frozen Food", url: "/" },
          { label: "Chicken", url: "/" },
          { label: "Beef", url: "/" },
        ],
      },
      {
        label: "Dog",
        url: "/",
        items: [
          { label: "Bowls & Feeders", url: "/" },
          { label: "Beds, Mats & Houses", url: "/" },
          { label: "Cages, Crates & Doors", url: "/" },
          { label: "Fleas & Ticks", url: "/" },
          { label: "Leashes, Collars & Muzzles", url: "/" },
          { label: "Carriers & Travel", url: "/" },
          { label: "Treats", url: "/" },
          { label: "Food", url: "/" },
          { label: "Grooming", url: "/" },
          { label: "Toys", url: "/" },
        ],
      },
      {
        label: "Cat",
        url: "/",
        items: [
          { label: "Trees, Condos & Scratchers", url: "/" },
          { label: "Bowls & Feeders", url: "/" },
          { label: "Beds, Mats & Houses", url: "/" },
          { label: "Cages, Crates & Doors", url: "/" },
          { label: "Carriers & Travel", url: "/" },
          { label: "Toys", url: "/" },
          { label: "Cat Treats", url: "/" },
          { label: "Grooming", url: "/" },
          { label: "Food", url: "/" },
          { label: "Litter & Toilet", url: "/" },
        ],
      },
      {
        label: "Breakfast, Choco & Snacks",
        url: "/",
        items: [
          { label: "Cakes & Sweets", url: "/" },
          { label: "Jams, Honey & Spreads", url: "/" },
          { label: "Oatmeals", url: "/" },
          { label: "Breakfast Cereals", url: "/" },
          { label: "Pancake & Waffle Mixes", url: "/" },
          { label: "Breakfast Bars", url: "/" },
          { label: "Instant Breakfast Drinks", url: "/" },
          { label: "Nuts & Legumes", url: "/" },
          { label: "Biscuit & Cookies", url: "/" },
          { label: "Chocolate & Candy", url: "/" },
          { label: "Chewing Gums & Mints", url: "/" },
          { label: "Chips & Crisps", url: "/" },
        ],
      },
      {
        label: "Beverages",
        url: "/",
        items: [
          { label: "Soft Drinks", url: "/" },
          { label: "Water", url: "/" },
          { label: "UHT, Milk & Milk Powder", url: "/" },
          { label: "Juices", url: "/" },
          { label: "Coffee", url: "/" },
          { label: "Powdered Drinks", url: "/" },
          { label: "Tea", url: "/" },
          { label: "Flavoring Syrup", url: "/" },
        ],
      },
      {
        label: "Food Staples",
        url: "/",
        items: [
          { label: "Condiment Dressing", url: "/" },
          { label: "Home Baking & Sugar", url: "/" },
          { label: "Cooking Ingredients", url: "/" },
          { label: "Noodles & Pasta", url: "/" },
          { label: "Jarred Food", url: "/" },
          { label: "Canned Food", url: "/" },
          { label: "Instant & Ready-to-Eat", url: "/" },
          { label: "Grains, Beans & Pulses", url: "/" },
          { label: "Rice", url: "/" },
          { label: "Oil", url: "/" },
        ],
      },
      {
        label: "Laundry & Household",
        url: "/",
        items: [
          { label: "Laundry", url: "/" },
          { label: "Pest Control", url: "/" },
          { label: "Tissue Paper", url: "/" },
          { label: "Cleaning", url: "/" },
          { label: "AirCare", url: "/" },
          { label: "Dishwashing", url: "/" },
          { label: "Foils & Cling Films", url: "/" },
        ],
      },
      {
        label: "Fish",
        url: "/",
        items: [
          { label: "Food", url: "/" },
          { label: "Aquarium Water Pumps", url: "/" },
          { label: "Aquarium Decorations", url: "/" },
          { label: "Aquarium Lighting", url: "/" },
          { label: "Aquarium Filters", url: "/" },
          { label: "Aquariums", url: "/" },
          { label: "Starter Kits", url: "/" },
          { label: "Aquarium Cleaning Tools", url: "/" },
          { label: "Aquarium Temp Control", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Home & Lifestyle",
    url: "/",
    Icon: House,
    items: [
      {
        label: "Laundry & Cleaning",
        url: "/",
        items: [
          { label: "Brushes, Sponges & Wipers", url: "/" },
          { label: "Brooms, Mops & Sweepers", url: "/" },
          { label: "Clothes Line & Drying Racks", url: "/" },
          { label: "Ironing Boards", url: "/" },
          { label: "Laundry Baskets & Hampers", url: "/" },
        ],
      },
      {
        label: "Tools, DIY & Outdoor",
        url: "/",
        items: [
          { label: "Paints", url: "/" },
          { label: "Fixtures & Plumbing", url: "/" },
          { label: "Lawn & Garden", url: "/" },
          { label: "Power Tools", url: "/" },
          { label: "Security", url: "/" },
          { label: "Electrical", url: "/" },
          { label: "Primers", url: "/" },
          { label: "Hand Tools", url: "/" },
          { label: "Home Build Up", url: "/" },
        ],
      },
      {
        label: "Bath",
        url: "/",
        items: [
          { label: "Bathroom Scales", url: "/" },
          { label: "Towel Rails & Warmers", url: "/" },
          { label: "Shower Caddies & Hangers", url: "/" },
          { label: "Bathroom Shelving", url: "/" },
          { label: "Bath Towels", url: "/" },
          { label: "Bathrobes", url: "/" },
          { label: "Bath Mats", url: "/" },
        ],
      },
      {
        label: "Stationery & Craft",
        url: "/",
        items: [
          { label: "Paper Products", url: "/" },
          { label: "Writing & Correction", url: "/" },
          { label: "Art Supplies", url: "/" },
          { label: "Packaging & Cartons", url: "/" },
          { label: "School & Office Equipment", url: "/" },
          { label: "Gifts & Wrapping", url: "/" },
          { label: "School Uniforms", url: "/" },
        ],
      },
      {
        label: "Furniture",
        url: "/",
        items: [
          { label: "Kitchen Furniture", url: "/" },
          { label: "Gaming Furniture", url: "/" },
          { label: "Home Office", url: "/" },
          { label: "Living Room", url: "/" },
          { label: "Bedroom", url: "/" },
        ],
      },
      {
        label: "Bedding",
        url: "/",
        items: [
          { label: "Comforters, Quilts & Duvets", url: "/" },
          { label: "Blankets & Throws", url: "/" },
          { label: "Pillows & Bolsters", url: "/" },
          { label: "Pillow Cases", url: "/" },
          { label: "Bedding Accessories", url: "/" },
          { label: "Bed Sheets", url: "/" },
          { label: "Mattress Protectors", url: "/" },
        ],
      },
      {
        label: "Decor",
        url: "/",
        items: [
          { label: "Mirrors", url: "/" },
          { label: "Cushions & Covers", url: "/" },
          { label: "Rugs & Carpets", url: "/" },
          { label: "Wall Stickers & Decals", url: "/" },
          { label: "Curtains", url: "/" },
          { label: "Artificial Flowers & Plants", url: "/" },
          { label: "Candles & Candleholders", url: "/" },
          { label: "Clocks", url: "/" },
          { label: "Vases & Vessels", url: "/" },
          { label: "Picture Frames", url: "/" },
        ],
      },
      {
        label: "Lighting",
        url: "/",
        items: [
          { label: "Wall Lights & Sconces", url: "/" },
          { label: "Ceiling Lights", url: "/" },
          { label: "Lighting Fixtures & Components", url: "/" },
          { label: "Light Bulbs", url: "/" },
          { label: "Lamp Shades", url: "/" },
          { label: "Outdoor Lighting", url: "/" },
          { label: "Table Lamps", url: "/" },
          { label: "Floor Lamps", url: "/" },
        ],
      },
      {
        label: "Media, Music & Books",
        url: "/",
        items: [
          { label: "eBooks", url: "/" },
          { label: "Books", url: "/" },
          { label: "Musical Instruments", url: "/" },
          { label: "Magazines", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Women's Fashion",
    url: "/",
    Icon: UserRound,
    items: [
      { label: "Girls Shoes", url: "/", items: [] },
      {
        label: "Girls Clothing",
        url: "/",
        items: [
          { label: "Socks & Tights", url: "/" },
          { label: "Jackets & Coats", url: "/" },
          { label: "Underwear & Sleepwear", url: "/" },
          { label: "Hats & Caps", url: "/" },
          { label: "Belts", url: "/" },
          { label: "Gloves, Scarves & Cold Weather", url: "/" },
          { label: "Dresses", url: "/" },
          { label: "Tops", url: "/" },
          { label: "Bottoms", url: "/" },
          { label: "Swimsuits", url: "/" },
          { label: "Hair Accessories", url: "/" },
          { label: "Hoodies", url: "/" },
        ],
      },
      {
        label: "Sleepwear & Innerwear",
        url: "/",
        items: [
          { label: "Tanks & Camisoles", url: "/" },
          { label: "Robe and Gown sets", url: "/" },
          { label: "Shapewear", url: "/" },
          { label: "Nightwear", url: "/" },
        ],
      },
      {
        label: "Bras, Panties & Lingerie",
        url: "/",
        items: [
          { label: "Beachwear and Bikinis", url: "/" },
          { label: "Lingerie Sets", url: "/" },
          { label: "Socks & Tights", url: "/" },
          { label: "Bras", url: "/" },
          { label: "Panties", url: "/" },
        ],
      },
      {
        label: "Unstitched Fabric",
        url: "/",
        items: [
          { label: "Sarees", url: "/" },
          { label: "Branded Unstitched", url: "/" },
        ],
      },
      {
        label: "Kurtas & Shalwar Kameez",
        url: "/",
        items: [
          { label: "Kurtis", url: "/" },
          { label: "Shalwar Kameez", url: "/" },
          { label: "Trousers & Palazzos", url: "/" },
        ],
      },
      {
        label: "Dresses & Skirts",
        url: "/",
        items: [
          { label: "Skirts", url: "/" },
          { label: "Formal Wear", url: "/" },
          { label: "Ethnic Dresses", url: "/" },
        ],
      },
      {
        label: "Winter Clothing",
        url: "/",
        items: [
          { label: "Jackets & Coats", url: "/" },
          { label: "Shrugs", url: "/" },
          { label: "Hoodies & Sweatshirts", url: "/" },
        ],
      },
      {
        label: "Pants, Jeans & Leggings",
        url: "/",
        items: [
          { label: "Jeggings", url: "/" },
          { label: "Shorts", url: "/" },
          { label: "Leggings", url: "/" },
          { label: "Pants", url: "/" },
          { label: "Jeans", url: "/" },
        ],
      },
      {
        label: "Tops",
        url: "/",
        items: [
          { label: "Tunics", url: "/" },
          { label: "Blouses & Shirts", url: "/" },
        ],
      },
      {
        label: "Muslim Wear",
        url: "/",
        items: [
          { label: "Dupattas, Stoles & Shawls", url: "/" },
          { label: "Scarves", url: "/" },
          { label: "Abayas & Hijabs", url: "/" },
          { label: "Hair Accessories", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Men's Fashion",
    url: "/",
    Icon: UserRound,
    items: [
      { label: "Boy's Shoes", url: "/", items: [] },
      {
        label: "Kurtas & Shalwar Kameez",
        url: "/",
        items: [
          { label: "Kurtas", url: "/" },
          { label: "Shalwar", url: "/" },
          { label: "Unstitched Fabric", url: "/" },
          { label: "Shawls", url: "/" },
        ],
      },
      {
        label: "Winter Clothing",
        url: "/",
        items: [
          { label: "Jackets & Coats", url: "/" },
          { label: "Hoodies & Sweatshirts", url: "/" },
        ],
      },
      {
        label: "Shorts, Joggers & Sweats",
        url: "/",
        items: [{ label: "Joggers & Sweats", url: "/" }],
      },
      {
        label: "Shirts & Polo",
        url: "/",
        items: [
          { label: "Polos", url: "/" },
          { label: "Casual Shirts", url: "/" },
          { label: "Formal Shirts", url: "/" },
        ],
      },
      { label: "T-Shirts & Tanks", url: "/", items: [] },
      {
        label: "Boy's Accessories",
        url: "/",
        items: [
          { label: "Socks", url: "/" },
          { label: "Belts", url: "/" },
          { label: "Hats & Caps", url: "/" },
        ],
      },
      {
        label: "Boy's Clothing",
        url: "/",
        items: [
          { label: "Kurtas & Shalwar Kameez", url: "/" },
          { label: "Shorts", url: "/" },
          { label: "T-Shirts & Shirts", url: "/" },
          { label: "Pants & Jeans", url: "/" },
          { label: "Underwear & Socks", url: "/" },
        ],
      },
      {
        label: "Accessories",
        url: "/",
        items: [
          { label: "Socks", url: "/" },
          { label: "Sunglasses", url: "/" },
          { label: "Gloves", url: "/" },
          { label: "Hats & Caps", url: "/" },
          { label: "Belts", url: "/" },
          { label: "Scarves", url: "/" },
          { label: "Ties & Bows", url: "/" },
        ],
      },
      {
        label: "Shoes",
        url: "/",
        items: [
          { label: "Shoes Accessories", url: "/" },
          { label: "Slip-Ons & Loafers", url: "/" },
          { label: "Khusa & Kolapuri", url: "/" },
          { label: "Formal Shoes", url: "/" },
          { label: "Flip Flops & Sandals", url: "/" },
          { label: "Sneakers", url: "/" },
          { label: "Boots", url: "/" },
        ],
      },
      {
        label: "Inner Wear",
        url: "/",
        items: [
          { label: "Thermal", url: "/" },
          { label: "Nightwear", url: "/" },
          { label: "Vests", url: "/" },
          { label: "Socks", url: "/" },
          { label: "Briefs", url: "/" },
          { label: "Trunk & Boxers", url: "/" },
        ],
      },
      {
        label: "Pants & Jeans",
        url: "/",
        items: [
          { label: "Jeans", url: "/" },
          { label: "Cargo", url: "/" },
          { label: "Chinos", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Watches, Bags & Jewellery",
    url: "/",
    Icon: Watch,
    items: [
      {
        label: "Women's Watches",
        url: "/",
        items: [
          { label: "Analog", url: "/" },
          { label: "Digital", url: "/" },
          { label: "Accessories", url: "/" },
        ],
      },
      {
        label: "Men's Watches",
        url: "/",
        items: [
          { label: "Analog", url: "/" },
          { label: "Accessories", url: "/" },
          { label: "Digital", url: "/" },
          { label: "Chronograph", url: "/" },
          { label: "Branded Watches", url: "/" },
        ],
      },
      {
        label: "Kid's Watches",
        url: "/",
        items: [
          { label: "Girls", url: "/" },
          { label: "Boys", url: "/" },
        ],
      },
      {
        label: "Mens Jewellery",
        url: "/",
        items: [
          { label: "Chains", url: "/" },
          { label: "Rings", url: "/" },
          { label: "Bracelets", url: "/" },
          { label: "Studs", url: "/" },
        ],
      },
      {
        label: "Womens Jewellery",
        url: "/",
        items: [
          { label: "Necklaces", url: "/" },
          { label: "Rings", url: "/" },
          { label: "Jewellery Sets", url: "/" },
          { label: "Anklets", url: "/" },
          { label: "Earrings", url: "/" },
          { label: "Bracelets", url: "/" },
        ],
      },
      {
        label: "Sunglasses & Eyewear",
        url: "/",
        items: [
          { label: "Lenses", url: "/" },
          { label: "Men Sunglasses", url: "/" },
          { label: "Women Sunglasses", url: "/" },
          { label: "Kids Sunglasses", url: "/" },
          { label: "Unisex Sunglasses", url: "/" },
          { label: "Kids Eyeglasses", url: "/" },
          { label: "Unisex Eyeglasses", url: "/" },
        ],
      },
      {
        label: "Womens Bags",
        url: "/",
        items: [
          { label: "Wristlets", url: "/" },
          { label: "Wallets & Accessories", url: "/" },
          { label: "Clutches", url: "/" },
          { label: "Backpacks", url: "/" },
          { label: "Top-Handle Bags", url: "/" },
          { label: "Tote Bags", url: "/" },
          { label: "Cross Body & Shoulder Bags", url: "/" },
        ],
      },
      {
        label: "Mens Bags",
        url: "/",
        items: [
          { label: "Backpacks", url: "/" },
          { label: "Crossbody Bags", url: "/" },
          { label: "Messenger Bags", url: "/" },
          { label: "Business Bags", url: "/" },
          { label: "Wallets & Cardholders", url: "/" },
          { label: "Cardholders & Keychains", url: "/" },
        ],
      },
      {
        label: "Luggage & Suitcase",
        url: "/",
        items: [
          { label: "Luggage", url: "/" },
          { label: "Laptop Bags", url: "/" },
          { label: "Travel Accessories", url: "/" },
        ],
      },
      {
        label: "Women's Accessories",
        url: "/",
        items: [
          { label: "Gloves", url: "/" },
          { label: "Belts", url: "/" },
          { label: "Hats & Caps", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Sports & Outdoor",
    url: "/",
    Icon: LandPlot,
    items: [
      {
        label: "Racket Sports",
        url: "/",
        items: [
          { label: "Badminton", url: "/" },
          { label: "Tennis", url: "/" },
          { label: "Squash", url: "/" },
        ],
      },
      {
        label: "Shoes & Clothing",
        url: "/",
        items: [
          { label: "Womens Shoes", url: "/" },
          { label: "Mens Shoes", url: "/" },
          { label: "Mens Clothing", url: "/" },
          { label: "Womens Clothing", url: "/" },
          { label: "Women Accessories", url: "/" },
          { label: "Men Accessories", url: "/" },
          { label: "Women Bags", url: "/" },
          { label: "Men Bags", url: "/" },
        ],
      },
      {
        label: "Sports Accessories",
        url: "/",
        items: [
          { label: "Water Bottles", url: "/" },
          { label: "Home Gym", url: "/" },
        ],
      },
      {
        label: "Fitness Gadgets",
        url: "/",
        items: [
          { label: "Fitness Trackers", url: "/" },
          { label: "Fitness Trackers Accessories", url: "/" },
        ],
      },
      {
        label: "Outdoor Recreation",
        url: "/",
        items: [
          { label: "Fishing", url: "/" },
          { label: "Water Sports", url: "/" },
          { label: "Skate Boards", url: "/" },
          { label: "Camping / Hiking", url: "/" },
          { label: "Cycling", url: "/" },
          { label: "Cycle accessories", url: "/" },
        ],
      },
      {
        label: "Supplements",
        url: "/",
        items: [
          { label: "Fat Burners", url: "/" },
          { label: "Post Workouts and Recovery", url: "/" },
          { label: "Pre Workouts", url: "/" },
          { label: "Proteins", url: "/" },
        ],
      },
      {
        label: "Team Sports",
        url: "/",
        items: [
          { label: "Baseballs", url: "/" },
          { label: "Hockey", url: "/" },
          { label: "Basket Ball", url: "/" },
          { label: "Volley balls", url: "/" },
          { label: "Cricket", url: "/" },
          { label: "Football", url: "/" },
        ],
      },
      {
        label: "Exercise & Fitness",
        url: "/",
        items: [
          { label: "Fitness Accessories", url: "/" },
          { label: "Treadmills", url: "/" },
          { label: "Exercise Bikes", url: "/" },
          { label: "Boxing, Martial Arts & MMA", url: "/" },
          { label: "Strength Training Equipments", url: "/" },
          { label: "Weight", url: "/" },
          { label: "Exercise Bands", url: "/" },
          { label: "Cardio Training Equipment", url: "/" },
          { label: "Yoga", url: "/" },
        ],
      },
    ],
  },
  {
    label: "Automotive & Motorbike",
    url: "/",
    Icon: Workflow,
    items: [
      {
        label: "Loaders & Rickshaw",
        url: "/",
        items: [
          { label: "Loaders", url: "/" },
          { label: "Auto Rikshaw", url: "/" },
        ],
      },
      {
        label: "Automotive",
        url: "/",
        items: [
          { label: "Car Tools & Equipment", url: "/" },
          { label: "Car Tires & Wheels", url: "/" },
          { label: "Car Oils & Fluids", url: "/" },
          { label: "Car Care", url: "/" },
          { label: "Car Exterior Accessories", url: "/" },
          { label: "Car Interior Accessories", url: "/" },
          { label: "Car Safety & Security", url: "/" },
          { label: "Car Electronics", url: "/" },
          { label: "Car Parts & Spares", url: "/" },
        ],
      },
      {
        label: "Motorcycle",
        url: "/",
        items: [
          { label: "Motorcycle Helmets", url: "/" },
          { label: "Sports Bikes", url: "/" },
          { label: "Standard Bikes", url: "/" },
          { label: "Electric Bikes", url: "/" },
          { label: "Motorcycle Parts & Spares", url: "/" },
          { label: "Motorcycle Oil & Fluids", url: "/" },
          { label: "Riding Gear", url: "/" },
          { label: "Motorcycle Accessories", url: "/" },
          { label: "ATVs & UTVs", url: "/" },
          { label: "Motorcycle Tires & Wheels", url: "/" },
        ],
      },
    ],
  },
];
